### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by numero-744**
IMO for a readme, Markdown would be easier to use XD

EDIT: but it is easier to copy-paste from/to the source files :smile:

### CODE REVIEW

**Comment by Dolu1990** [comment]
i think we should keep some doc about how to generate the doc without docker ^^

**Comment by numero-744** [comment]
@Dolu1990 I think it is still in [the README](https://github.com/SpinalHDL/SpinalDoc-RTD/blob/572c68518ce5221b37bdcf32b1d9b7266787e37c/README.rst). There is venv, Docker and native.

**Comment by numero-744** [comment]
The readme? It is an RST file. A Md file would work to as it is not used by Sphinx?

**Comment by Readon** [comment]
It's not abort by the compilation of rst.
it's about finding the link, as [action](https://github.com/SpinalHDL/SpinalDoc-RTD/actions/runs/3488477940/jobs/5837453219) shows.?

**Comment by Dolu1990** [comment]
Hoo right, i mixed deployement with offline generation XD
Thanks

**Pull request merged**
