### PR TITLE
fix: last example "Simulation support"

### PR DESCRIPTION
**Pull request by numero-744**
It was not building. Now it builds but it still does not pass the test.

The test fails: `Timeout trigger after 10000 units of time`

### CODE REVIEW

**Comment by Dolu1990** [comment]
I will check why it isn't passing

**Comment by Dolu1990** [comment]
For me it is fine : 
[Done] Simulation done in 31.952 ms

**Comment by numero-744** [comment]
For me too it worked the first time, maybe an issue about randomization?

**Comment by numero-744** [comment]
Watch this seed: 172735708

**Comment by numero-744** [comment]
I have added a `println` in each `StreamMonitor`, it seems to push but never pop.

**Comment by numero-744** [comment]
Merge if okay for you

**Comment by Dolu1990** [comment]
Ahhh nice catch, yes flush randomization issue ^^
Thanks

**Pull request merged**
