### PR TITLE
No more convet-wrapper ?

### PR DESCRIPTION
**Pull request by Dolu1990**
I don't know, this line just make my setup not work, and commenting it out doesn't seems to break anything

### CODE REVIEW

**Comment by andreasWallner** [comment]
I think the idea was to break the build in case the correct environment is not sourced (which in turn breaks the multi-version build)

**Comment by Dolu1990** [comment]
thing is even when i sourced the environnement, it doesn't fix it. (on a very recent Mint distrib)

**Comment by andreasWallner** [comment]
because it can't find `convert-wrapper` - weird...
could you check your PATH after loading it and whether the script is executable?

In the end I think it doesn't matter too much for a quick local run, only if one wants to build all the old versions as well... (and on CI, but there the script still seems to work as expected)

**Comment by Dolu1990** [comment]
hmm i just tried again using venv, and it worked directly.
I don't know what i was doing wrong, maybe didn't sourced things properly XD

sorry for the noise XD

**Comment by mrcmry** [comment]
Deleted this trivial branch not relevant anymore for cleanup.

**Pull request closed without merging**
