### PR TITLE
ci: pdf generation with docker

### LINKED ISSUE #132: ci: generate pdf
PDF generation is done in two phases: rst->tex & tex->pdf. I get an error in the first phase.

Expected: create latex files

Actual:

```zsh
% make latex
Extension error:
convert exited with error:
[stderr]
b"convert-im6.q16: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1966.\nconvert-im6.q16: unable to open file `/tmp/magick-js2pMmJNdpHh0gLO_sYh6hvy9N2dsNJn': No such file or directory @ error/constitute.c/ReadImage/614.\nconvert-im6.q16: no images defined `/docs/docs/doctrees/images/process_rtl.png' @ error/convert.c/ConvertImageCommand/3229.\n"
[stdout]
b''
make: *** [Makefile:19: latex] Error 2
```

### PR DESCRIPTION
**Pull request by numero-744**
Fix #132 

I still have to add it to GitHub actions, but there is still discussion needed in #132 about this.

### CODE REVIEW

**Comment by numero-744** [comment]
Oooh check failed because of https://github.com/SpinalHDL/SpinalHDL/pull/913, I will have update links in another PR after https://github.com/SpinalHDL/SpinalHDL/pull/918 is merged

**Comment by numero-744** [comment]
I am editing [`.github/workflows/push-doc.yml`](https://github.com/numero-744/SpinalDoc-RTD/blob/6925bbba3adbba1313564da183e6f28f4163103c/.github/workflows/push-doc.yml#L28-L41) and I notice the redirection. I am wondering, is it possible to push a page right on https://spinalhdl.github.io/ with a redirection?

**Comment by numero-744** [comment]
It's alive! https://numero-744.github.io/SpinalDoc-RTD/

I do some fixes for caching then I update this PR.

**Comment by numero-744** [comment]
Okay so for now it seems I fail with caching the docker image… But maybe it is just because cache is used only for when history goes forward so I don't know. Anyway, it is not a big deal as it is only on release, not for PRs.

**Comment by numero-744** [comment]
@wifasoi @Dolu1990 ready for review :heart:

**Comment by Readon** [comment]
Ahhh, it is not mergable now, due to the duplicated modification on README i think.

**Comment by Readon** [comment]
Why we need to change the files in .github directory when the target is just generate a pdf by docker?

**Comment by numero-744** [comment]
@Readon the conflict is fixed now.

Because the idea is to provide access to the PDF from the site like in https://github.com/SpinalHDL/SpinalDoc-RTD/issues/132#issuecomment-1291838378 or in live demo: https://numero-744.github.io/SpinalDoc-RTD/master/

**Comment by Readon** [comment]
> @Readon the conflict is fixed now.
> 
> Because the idea is to provide access to the PDF from the site like in [#132 (comment)](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/132#issuecomment-1291838378) or in live demo: https://numero-744.github.io/SpinalDoc-RTD/master/

Ahhh, I guess you merged the two targets into one.
1. generate pdf with docker.
2. automatically generate & publish pdf file on corresponding website.

**Comment by numero-744** [comment]
Yes, using docker was more a way to ease setting things up (can be tested locally, really useful for debug)

**Comment by Readon** [comment]
> Yes, using docker was more a way to ease setting things up (can be tested locally, really useful for debug)

Yes, docker is very good. 
The link to the generated pdf is hidden too deep.

However, I'm not familiar with this, so I can't give any more advice. :)

**Comment by Readon** [comment]
Maybe we can merge this first to see if there is any feedback.

**Comment by numero-744** [comment]
>  Except that the link to the generated pdf is hidden too deep.

This is from an unreleased feature of multiversion I was pointed to: https://github.com/SpinalHDL/SpinalDoc-RTD/issues/132#issuecomment-1290327628

I'm okay with it: you have a button with versions, you find old versions and different formats. But I'm working on a big refactoring of the docs (PR not open yet), I'll take it into consideration, to make this `v:master` button more known.

**Comment by Readon** [comment]
> > Except that the link to the generated pdf is hidden too deep.
> 
> This is from an unreleased feature of multiversion I was pointed to: [#132 (comment)](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/132#issuecomment-1290327628)
> 
> I'm okay with it: you have a button with versions, you find old versions and different formats. But I'm working on a big refactoring of the docs (PR not open yet), I'll take it into consideration, to make this `v:master` button more known.

Maybe another PR is better to keep the repo's history clean.

**Comment by numero-744** [comment]
Yea, will be a really big PR on its own, no need to mix it with other things XD

**Pull request merged**
