### PR TITLE
Add SystemRDL RegIf exporter documentation

### PR DESCRIPTION
**Pull request by MarekPikula**
Also, there are some fixes in the RegIf documentation.

Relates to SpinalHDL/SpinalHDL#900.

### CODE REVIEW

**Comment by MarekPikula** [comment]
@numero-744

**Comment by numero-744** [comment]
LGTM, waiting for https://github.com/SpinalHDL/SpinalHDL/pull/900 to be merged first

**Comment by numero-744** [comment]
Can anyone approve the workflow to check if the PR passes it?

**Comment by Dolu1990** [comment]
I don't know who approved it, but it passed ^^

**Pull request merged**
